### ISSUE TITLE
Use shorter lifetimes

### ISSUE THREAD

**Issue by alexkreidler** [najamelan/async_nursery#1]
Right now, I use the function: `fn nurse( &self, fut: impl Future<Output = Out> + Send + 'static ) -> Result<(), NurseErr>;` This unfortunately means I can't use references in my `async fn` with a lifetime less than `'static`, which is quite inconvenient.

I'm not really sure of the complexity of changing that, but I'd appreciate any thoughts you have on it.

**Comment by najamelan** [comment]
You can't spawn non static futures on any executor without unsafe. The problem is that you can use `mem::forget` to leak the nursery, which would than outlive it's parent scope, which might hold the pointed to value. Thus when the stack frame ends, that value get's dropped, but the nursery can outlive it and still run code that has a reference to that memory. That is a memory safety issue which is not allowed in safe rust.

The only crate that can help you here is https://docs.rs/async-scoped which requires you use unsafe. If you want to go that path, I would suggest you use async-scoped. Unless there is some very good arguments for it and it can be implemented cleanly, I havent any plans to add such an unsafe API to async_nursery. That being said, if you have some very compelling argument, please share.

Some more discussion about the issue can be found here: https://github.com/tokio-rs/tokio/issues/1879#issuecomment-567011455

**Comment by najamelan** [comment]
ps: I'm adding this to the readme: https://github.com/najamelan/async_nursery/commit/6c2620e98bbf51a53254f3ecae186a3eb54f7ad1#diff-04c6e90faac2675aa89e2176d2eec7d8R69

**Comment by alexkreidler** [comment]
Thanks!

**Comment by sftse** [comment]
It is not possible in general to use arbitrary lifetimes, but there's prior art in doing so with `smol` for lifetimes that outlive the executor.

```rust
struct Executor<'a> {...}

impl<'a> Executor<'a> {
    fn spawn<T>(&self, f: impl Future<Output = T> + Send + 'a) -> Task<T> 
        where T: Send + 'a {...}
}
let x: Vec<u8> = Vec::new();
let ex = Executor::new();
ex.spawn(async { &x });
```

Would it be conceivable to add a similar api to the nursery? The nursery would need to be bounded by borrowing from the executor, and to spawn a non-'static task onto Tokio either `async_executors` or `async_nursery` would need an unsafe block.
