### ISSUE TITLE
Possibility to split the core into a separate crate?

### ISSUE THREAD

**Issue by teohhanhui** [najamelan/async_nursery#2]
For example, in my library I have an `interval` function which takes a `Nurse<_>` and calls `NurseExt<_>` methods on it:

https://github.com/teohhanhui/callbag-rs/blob/d0a7523018854a44a3c4d1687fefa893afa3beb0/src/interval.rs

Currently, every user of my library would be forced to bring in a whole lot of dependencies, even if they don't use this `interval` function.

This is because `async_nursery` depends on `async_executors` and `futures`.

From what I can see, if we were to split into a crate such as `async_nursery_core`, which includes:

- https://github.com/najamelan/async_nursery/blob/3c6c55aa9900c31c86fdce709395a7dc3e575aaa/src/error.rs
https://github.com/najamelan/async_nursery/blob/3c6c55aa9900c31c86fdce709395a7dc3e575aaa/src/local_nurse.rs
- https://github.com/najamelan/async_nursery/blob/3c6c55aa9900c31c86fdce709395a7dc3e575aaa/src/nurse.rs

It only needs to have these dependencies:

- `futures-channel`:
    - `TrySendError`
- `futures-task`:
    - `FutureObj`
    - `LocalFutureObj`
    - `SpawnError`

And we shouldn't run afoul of coherence rules, since `struct Nursery<_, _>` and `struct NurseryStream<_, _>` will both still be defined in the `async_nursery` crate.

**Comment by najamelan** [comment]
Hi, sorry I missed your issue over the last few days. I will look into it. I think if there are unnecessary dependencies, we can hide them behind a feature. That way they can be avoided without creating more crate ;).

**Comment by najamelan** [comment]
I'm having a look at your code to try and understand what you are trying to do, but I admit it's not quite clear. When you take an `impl Nurse` as a parameter you are saying to your clients that they have to manage the lifetime of the spawned futures, but the docs on your method don't give any hint to the user what that entails, eg. how long to keep them alive? In general I most use the nursery to tie the lifetime of tasks to the lifetime of an object, like a network connection that spawns tasks to handle requests, and when the connection closes, it doesn't make sense to keep processing any requests as we wont be able to send the response.

Know that you have other options as well to leave the user more flexibility. If you want to create an interval, I would personally return a `futures::Stream`. That way the users spawn/poll it however they like. Or you can have an object that implements [`Observable`](https://docs.rs/pharos/latest/pharos/trait.Observable.html) and has an async `start` function.

You can also take `SpawnHandle` and return the `JoinHandle` from your function, or you can make an async function the user calls and let them spawn it, or you can just take an `impl futures::task::Spawn` and hint in documentation that users can pass in a nursery if they want to control the lifetime, as `Nursery` implements that trait.

**Comment by najamelan** [comment]
Another comment. I don't think you can poll `futures_timer::Delay` to completion several times. Eg. it's not a stream. Which means this is quite tricky. You should create a new delay  every time, but what if some time has passed? It depends how reliable your interval must be, but the user controls when they poll, so when they poll to late it will extend the delay. You could have a look at the [interval in async_std](https://docs.rs/async-std/latest/async_std/stream/fn.interval.html) to see how they do it. They also implement `Stream`, so you can also use that and [map](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.map) it to a number and return `impl Stream`.

**Comment by teohhanhui** [comment]
> I don't think you can poll `futures_timer::Delay` to completion several times

It is supported:

https://github.com/async-rs/futures-timer/blob/30e562cdde45b8a6ee93d22094df8664ff8dfdfb/tests/smoke.rs#L15-L31

**Comment by najamelan** [comment]
Ok, thanks for clarifying. I will try to release a version with a feature soon allowing to only get the traits. I do want to point out the benefit will probably be smaller than you think. Except if users are implementing the `Nurse` trait themselves, they will have to use the `Nursery` from _async_nursery_ anyway, in which case they will get the same dependencies. 

Also, async_executors is really small when no features are enabled, and none are by default (it's just a few traits). One thing I noticed is that I had not disabled default features on the futures crate by default so there is a small margin for improvement there. However, again most users of async will end up with the futures crate included in their project regardless. I am also adding a method to `Nursery` that allows a user to add a `JoinHandle` to the nursery for a task that is already spawned. The should make it more flexible if an API would take `SpawnHandle` and return a `JoinHandle`.

As for the `Spawn` trait, async_executors implements it for _tokio_ and _async-std_ executors and `Nursery` implements it as well. So it allows the biggest flexibility. However the `Nurse` trait is currently not implemented for anything but the `Nursery` as far as I know. Taking a `Nurse` rather than a `Spawn` basically just says to your users that your API can only work in a structured concurrency model. To be clear I'm not saying it's wrong to do so, just want to make sure you understand your options and their trade-offs.

**Comment by teohhanhui** [comment]
>  I do want to point out the benefit will probably be smaller than you think. Except if users are implementing the `Nurse` trait themselves, they will have to use the `Nursery` from async_nursery anyway, in which case they will get the same dependencies.

The benefit is for users of my library who don't use the `callbag::interval` function at all. Currently the dependencies are pulled in regardless.

> Taking a `Nurse` rather than a `Spawn` basically just says to your users that your API can only work in a structured concurrency model. To be clear I'm not saying it's wrong to do so, just want to make sure you understand your options and their trade-offs.

I'm not really sure to be honest, but in practical terms I don't see any downsides to taking an `impl Nurse`.

**Comment by najamelan** [comment]
Im working on a release for _async_executors_. Since both will be breaking changes, I'm trying to roll that out first. New version will be up in the next few days.

> I'm not really sure to be honest, but in practical terms I don't see any downsides to taking an `impl Nurse`.

The downside is restricting your users options. You basically ask them to guarantee a commitment to structured concurrency. That is that they will not let the task be orphaned. From what I can tell you don't need such a strong commitment. For example if they are just going to let the task tick x times and it will then end automatically, it might be fine to just spawn it. Or if they just want to let it tick for the entire lifetime of their program. That being said I don't know your lib as well as you do of course. It just seemed odd.

> The benefit is for users of my library who don't use the `callbag::interval` function at all. Currently the dependencies are pulled in regardless.

If it's an optional feature of your library, the best way to make compilation lighter is to put it behind an cargo feature. You can even make the feature enabled by default so most users don't have to deal with it, but someone who wants to shed dependencies can turn it off.

**Comment by teohhanhui** [comment]
> If it's an optional feature of your library, the best way to make compilation lighter is to put it behind an cargo feature. You can even make the feature enabled by default so most users don't have to deal with it, but someone who wants to shed dependencies can turn it off.

Yeah, that's already the case. Haha... Just trying to shed dependencies by default. ☺️

**Comment by najamelan** [comment]
> It's always an infinite stream at the provided interval.

I saw the examples using `take(5)` and assumed the task would end after that. If it's not the case do realize that awaiting the `NurseryStream` awaits until all nursed tasks end. So in that case the program would never terminate. The way to forcefully end the tasks in that case is to drop the `NurseryStream`, but I would say in your case the closing the `Sink` is the most recommended way of controlling the lifetime of such a task. 

How bad orphaning is depends. One advantage of structured concurrency is that you can bubble up errors, but if you drop the `NurseryStream` to forcefully end the tasks, you wont get those for tasks that were still running. The other is that one timer ticking for the lifetime of a program probably is fine but when dozens start going left and right, that seems bad (eg. its a memory leak).

**Comment by najamelan** [comment]
New version 0.4 has been released. When you add the dependency with `default-features = false` you will only get the traits and not the dependencies. Feel free to let me know if there's anything else.
